sudo: required
language: python
services:
- docker
before_install:
- docker build -t makerdao/vulcan0x .
script:
 - "./test.sh"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
